<a href="https://colab.research.google.com/github/vijayshreesunshine-ux/data-science-masters/blob/main/numpypart1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
l=[1,2,3,4,5,6]

In [5]:
arr=np.array(l)

In [6]:
type(arr)

numpy.ndarray

In [7]:
np.asarray(l)

array([1, 2, 3, 4, 5, 6])

In [8]:
arr1= np.array([[1,2,3],[2,3,4]])

In [11]:
arr.ndim

1

In [12]:
arr1.ndim

2

In [13]:
mat=np.matrix(l)

In [14]:
mat

matrix([[1, 2, 3, 4, 5, 6]])

In [15]:
np.asanyarray(l)

array([1, 2, 3, 4, 5, 6])

In [16]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4, 5, 6]])

In [17]:
arr

array([1, 2, 3, 4, 5, 6])

In [18]:
a=arr

In [19]:
a

array([1, 2, 3, 4, 5, 6])

In [20]:
arr

array([1, 2, 3, 4, 5, 6])

In [21]:
arr[0]=100

In [22]:
arr

array([100,   2,   3,   4,   5,   6])

In [23]:
a

array([100,   2,   3,   4,   5,   6])

In [24]:
b=np.copy(arr)

In [25]:
b[0]=234

In [26]:
b

array([234,   2,   3,   4,   5,   6])

In [27]:
arr

array([100,   2,   3,   4,   5,   6])

In [28]:
np.fromfunction(lambda i,j:i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [29]:
np.fromfunction(lambda i,j:i*j,(3,3))


array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [30]:
 iterable= list (i*i for i in range (5))

In [31]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [33]:
np.fromstring('23 45 56 ',sep=' ')

array([23., 45., 56.])

In [34]:
arr

array([100,   2,   3,   4,   5,   6])

In [35]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [36]:
arr.size

6

In [37]:
arr1.size

6

In [38]:
arr.shape

(6,)

In [39]:
arr1.shape

(2, 3)

In [41]:
arr1.dtype

dtype('int64')

In [42]:
list(range(5))

[0, 1, 2, 3, 4]

In [43]:
list(range(0,12))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [44]:
list(range(2.4,12.5))

TypeError: 'float' object cannot be interpreted as an integer

In [45]:
np.arange(.4,10.4,0.2)

array([ 0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,  2.2,  2.4,
        2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,  4.4,  4.6,
        4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,  6.6,  6.8,
        7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,  8.8,  9. ,
        9.2,  9.4,  9.6,  9.8, 10. , 10.2])

In [46]:
list(np.arange(.4,10.4,0.2))

[np.float64(0.4),
 np.float64(0.6000000000000001),
 np.float64(0.8000000000000002),
 np.float64(1.0000000000000002),
 np.float64(1.2000000000000002),
 np.float64(1.4000000000000004),
 np.float64(1.6000000000000005),
 np.float64(1.8000000000000003),
 np.float64(2.0000000000000004),
 np.float64(2.2000000000000006),
 np.float64(2.400000000000001),
 np.float64(2.6000000000000005),
 np.float64(2.8000000000000007),
 np.float64(3.000000000000001),
 np.float64(3.2000000000000006),
 np.float64(3.400000000000001),
 np.float64(3.600000000000001),
 np.float64(3.800000000000001),
 np.float64(4.000000000000002),
 np.float64(4.200000000000001),
 np.float64(4.400000000000002),
 np.float64(4.600000000000001),
 np.float64(4.800000000000002),
 np.float64(5.000000000000002),
 np.float64(5.200000000000002),
 np.float64(5.400000000000002),
 np.float64(5.600000000000002),
 np.float64(5.8000000000000025),
 np.float64(6.000000000000002),
 np.float64(6.200000000000002),
 np.float64(6.400000000000002),
 np.float

In [47]:
np.linspace(1,5,45)

array([1.        , 1.09090909, 1.18181818, 1.27272727, 1.36363636,
       1.45454545, 1.54545455, 1.63636364, 1.72727273, 1.81818182,
       1.90909091, 2.        , 2.09090909, 2.18181818, 2.27272727,
       2.36363636, 2.45454545, 2.54545455, 2.63636364, 2.72727273,
       2.81818182, 2.90909091, 3.        , 3.09090909, 3.18181818,
       3.27272727, 3.36363636, 3.45454545, 3.54545455, 3.63636364,
       3.72727273, 3.81818182, 3.90909091, 4.        , 4.09090909,
       4.18181818, 4.27272727, 4.36363636, 4.45454545, 4.54545455,
       4.63636364, 4.72727273, 4.81818182, 4.90909091, 5.        ])

In [49]:
np.logspace(1,5,10,base=3)

array([  3.        ,   4.88849467,   7.96579337,  12.98024613,
        21.151288  ,  34.46598619,  56.16226322,  91.51630808,
       149.12566131, 243.        ])

In [50]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [51]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [57]:
np.zeros((4,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [58]:
np.zeros((3,4,4,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [59]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [60]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [62]:
arr2  = np.ones((3,4 ))

In [65]:
 arr2+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [66]:
arr2*4

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [67]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [68]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [69]:
import pandas as pd

In [70]:
pd.DataFrame(arr1)

0  1  2
0  1  2  3
1  2  3  4

In [72]:
np.random.rand(2,3)

array([[0.8138437 , 0.64800503, 0.21517373],
       [0.66583483, 0.74623229, 0.12295926]])

In [73]:
np.random.randn(2,3)

array([[ 0.78243095,  1.37882428, -1.21867739],
       [-0.32439381, -0.21761264,  1.05405132]])

In [75]:
arr2 = np.random.randint(1,5,(3,4))

In [76]:
arr2.size

12

In [77]:
arr2.shape

(3, 4)

In [79]:
arr.reshape(3,2)

array([[100,   2],
       [  3,   4],
       [  5,   6]])

In [80]:
arr2.reshape(3,4,1,1)

array([[[[3]],

        [[3]],

        [[1]],

        [[4]]],


       [[[3]],

        [[3]],

        [[4]],

        [[1]]],


       [[[3]],

        [[4]],

        [[2]],

        [[4]]]])

In [81]:
arr4=np.random.randint(1,10,(5,6))

In [83]:
arr4

array([[1, 9, 4, 5, 6, 6],
       [5, 1, 7, 1, 1, 5],
       [6, 8, 7, 6, 8, 3],
       [8, 1, 4, 2, 4, 1],
       [1, 3, 6, 4, 7, 1]])

In [84]:
arr4>8

array([[False,  True, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [85]:
arr4[arr4>8]

array([9])

In [86]:
arr1[0,[0,1]]

array([1, 2])

In [91]:
arr4[2:4,[2,3]]

array([[7, 6],
       [4, 2]])

In [93]:
arr5=np.random.randint(1,10,(5,6))
arr6=np.random.randint(1,10,(5,6))

In [95]:
arr6

array([[2, 4, 1, 6, 4, 6],
       [9, 9, 2, 7, 4, 1],
       [7, 8, 2, 4, 9, 8],
       [9, 2, 7, 9, 7, 9],
       [5, 2, 9, 2, 9, 9]])

In [94]:
arr5

array([[8, 2, 5, 9, 1, 4],
       [5, 6, 8, 2, 5, 7],
       [1, 8, 7, 5, 1, 1],
       [7, 2, 1, 9, 7, 5],
       [6, 9, 8, 6, 1, 3]])

In [96]:
arr5+arr6

array([[10,  6,  6, 15,  5, 10],
       [14, 15, 10,  9,  9,  8],
       [ 8, 16,  9,  9, 10,  9],
       [16,  4,  8, 18, 14, 14],
       [11, 11, 17,  8, 10, 12]])

In [97]:
arr5-arr6

array([[ 6, -2,  4,  3, -3, -2],
       [-4, -3,  6, -5,  1,  6],
       [-6,  0,  5,  1, -8, -7],
       [-2,  0, -6,  0,  0, -4],
       [ 1,  7, -1,  4, -8, -6]])

In [98]:
arr5*arr6

array([[16,  8,  5, 54,  4, 24],
       [45, 54, 16, 14, 20,  7],
       [ 7, 64, 14, 20,  9,  8],
       [63,  4,  7, 81, 49, 45],
       [30, 18, 72, 12,  9, 27]])

In [102]:
arr6 @ arr5.T

array([[111, 116,  81, 135, 114],
       [171, 156, 135, 179, 200],
       [159, 208, 122, 206, 187],
       [235, 229, 135, 249, 216],
       [152, 221, 112, 174, 168]])

In [103]:
arr5/0

/tmp/ipython-input-4034504109.py:1: RuntimeWarning: divide by zero encountered in divide
  arr5/0


array([[inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf]])

In [104]:
#broadcasting

In [105]:
arr=np.zeros((3,4))

arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [106]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [108]:
a=np.array([1,2,3,4])

In [109]:
arr+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [110]:
b= np.array([3,4,5])

In [114]:
arr + b.reshape(3,1)

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [115]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [1.41421356, 1.73205081, 2.        ]])

In [116]:
np.exp(arr1)

array([[ 2.71828183,  7.3890561 , 20.08553692],
       [ 7.3890561 , 20.08553692, 54.59815003]])

In [117]:
np.log10(arr1)

array([[0.        , 0.30103   , 0.47712125],
       [0.30103   , 0.47712125, 0.60205999]])

In [118]:
np.mean(arr1)

np.float64(2.5)