<a href="https://colab.research.google.com/github/vijayshreesunshine-ux/data-science-masters/blob/main/numpypart2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5])

In [3]:
arr

array([1, 2, 3, 4, 5])

In [4]:
arr=np.random.randint(1,10,(4,4))

In [5]:
arr

array([[4, 7, 1, 2],
       [9, 9, 6, 8],
       [8, 4, 1, 7],
       [8, 5, 3, 5]])

In [6]:
arr.T

array([[4, 9, 8, 8],
       [7, 9, 4, 5],
       [1, 6, 1, 3],
       [2, 8, 7, 5]])

In [7]:
arr.flatten()

array([4, 7, 1, 2, 9, 9, 6, 8, 8, 4, 1, 7, 8, 5, 3, 5])

In [8]:
np.expand_dims(arr,axis=1)

array([[[4, 7, 1, 2]],

       [[9, 9, 6, 8]],

       [[8, 4, 1, 7]],

       [[8, 5, 3, 5]]])

In [9]:
np.expand_dims(arr,axis=0)

array([[[4, 7, 1, 2],
        [9, 9, 6, 8],
        [8, 4, 1, 7],
        [8, 5, 3, 5]]])

In [10]:
data=np.array([[1],[2],[3]])

In [11]:
np.squeeze(data)

array([1, 2, 3])

In [12]:
np.repeat(data,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [13]:
np.roll(data,2)

array([[2],
       [3],
       [1]])

In [14]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [15]:
arr1=np.random.randint(1,10,(3,4))
arr2=np.random.randint(1,10,(3,4))

In [19]:
arr1+arr2

array([[10,  5, 11,  7],
       [11,  5, 11, 10],
       [ 3, 11,  7, 10]])

In [17]:
arr1-arr2

array([[-2,  1,  3, -3],
       [ 5,  3, -7, -8],
       [ 1, -7, -1, -4]])

In [20]:
arr1

array([[4, 3, 7, 2],
       [8, 4, 2, 1],
       [2, 2, 3, 3]])

In [21]:
arr2

array([[6, 2, 4, 5],
       [3, 1, 9, 9],
       [1, 9, 4, 7]])

In [22]:
arr1^arr2

array([[ 2,  1,  3,  7],
       [11,  5, 11,  8],
       [ 3, 11,  7,  4]])

In [23]:
~arr1

array([[-5, -4, -8, -3],
       [-9, -5, -3, -2],
       [-3, -3, -4, -4]])

In [24]:
-arr1

array([[-4, -3, -7, -2],
       [-8, -4, -2, -1],
       [-2, -2, -3, -3]])

In [25]:
arr=np.array(['sudh','kumar'])

In [26]:
arr

array(['sudh', 'kumar'], dtype='<U5')

In [27]:
np.char.upper(arr)

array(['SUDH', 'KUMAR'], dtype='<U5')

In [28]:
np.char.capitalize(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [29]:
np.char.title(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [30]:
arr1

array([[4, 3, 7, 2],
       [8, 4, 2, 1],
       [2, 2, 3, 3]])

In [31]:
np.sin(arr1)

array([[-0.7568025 ,  0.14112001,  0.6569866 ,  0.90929743],
       [ 0.98935825, -0.7568025 ,  0.90929743,  0.84147098],
       [ 0.90929743,  0.90929743,  0.14112001,  0.14112001]])

In [32]:
np.tan(arr1)

array([[ 1.15782128, -0.14254654,  0.87144798, -2.18503986],
       [-6.79971146,  1.15782128, -2.18503986,  1.55740772],
       [-2.18503986, -2.18503986, -0.14254654, -0.14254654]])

In [33]:
np.power(arr1,7)

array([[  16384,    2187,  823543,     128],
       [2097152,   16384,     128,       1],
       [    128,     128,    2187,    2187]])

In [34]:
np.median(arr1)

np.float64(3.0)

In [35]:
np.std(arr1)

np.float64(2.0190069065976197)

In [36]:
np.var(arr1)

np.float64(4.07638888888889)

In [37]:
np.min(arr1)

np.int64(1)

In [38]:
arr1-arr2

array([[-2,  1,  3, -3],
       [ 5,  3, -7, -8],
       [ 1, -7, -1, -4]])

In [40]:
np.subtract(arr1,arr2)

array([[-2,  1,  3, -3],
       [ 5,  3, -7, -8],
       [ 1, -7, -1, -4]])

In [41]:
np.mod(arr1,arr2)

array([[4, 1, 3, 2],
       [2, 0, 2, 1],
       [0, 2, 3, 3]])

In [42]:
np.power(arr1,arr2)

array([[4096,    9, 2401,   32],
       [ 512,    4,  512,    1],
       [   2,  512,   81, 2187]])

In [43]:
np.mean(arr1)

np.float64(3.4166666666666665)

In [44]:
np.median(arr1)

np.float64(3.0)

In [45]:
#sort,search,counting functions

In [51]:
arr =np.array([2,3,4,5,6,67,98,54,32,12,354])

In [52]:
arr

array([  2,   3,   4,   5,   6,  67,  98,  54,  32,  12, 354])

In [53]:
np.sort(arr)

array([  2,   3,   4,   5,   6,  12,  32,  54,  67,  98, 354])

In [54]:
np.searchsorted(arr,34)

np.int64(5)

In [55]:
arr1=np.array([0,345,454,0,0,0,0,0])

In [56]:
np.count_nonzero(arr1)

2

In [57]:
np.where(arr1>0)

(array([1, 2]),)

In [58]:
np.extract(arr>2,arr)

array([  3,   4,   5,   6,  67,  98,  54,  32,  12, 354])

In [59]:
#byte swappinng

In [60]:
arr1

array([  0, 345, 454,   0,   0,   0,   0,   0])

In [61]:
arr.byteswap()

array([ 144115188075855872,  216172782113783808,  288230376151711744,
        360287970189639680,  432345564227567616, 4827858800541171712,
       7061644215716937728, 3891110078048108544, 2305843009213693952,
        864691128455135232, 7061925690693648384])

In [62]:
arr

array([  2,   3,   4,   5,   6,  67,  98,  54,  32,  12, 354])

In [63]:
arr.byteswap(True)

array([ 144115188075855872,  216172782113783808,  288230376151711744,
        360287970189639680,  432345564227567616, 4827858800541171712,
       7061644215716937728, 3891110078048108544, 2305843009213693952,
        864691128455135232, 7061925690693648384])

In [64]:
arr

array([ 144115188075855872,  216172782113783808,  288230376151711744,
        360287970189639680,  432345564227567616, 4827858800541171712,
       7061644215716937728, 3891110078048108544, 2305843009213693952,
        864691128455135232, 7061925690693648384])

In [65]:
arr1

array([  0, 345, 454,   0,   0,   0,   0,   0])

In [66]:
a=np.copy(arr1)

In [67]:
b=arr1.view()
#or b=arr1 swallow copy case

In [68]:
b

array([  0, 345, 454,   0,   0,   0,   0,   0])

In [69]:
b[0]=234

In [70]:
 b

array([234, 345, 454,   0,   0,   0,   0,   0])

In [71]:
arr1

array([234, 345, 454,   0,   0,   0,   0,   0])

In [72]:
#matrix library

In [73]:
import numpy.matlib as nm

In [74]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [75]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [76]:
nm.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [77]:
#linear algebra

In [78]:
arr1

array([234, 345, 454,   0,   0,   0,   0,   0])

In [79]:
arr2

array([[6, 2, 4, 5],
       [3, 1, 9, 9],
       [1, 9, 4, 7]])

In [81]:
arr1 = np.random.randint([[2,3],[4,5]])

In [82]:
arr2=np.random.randint([[5,3],[2,5]])

In [83]:
arr2

array([[3, 0],
       [0, 0]])

In [84]:
arr1

array([[1, 2],
       [3, 0]])

In [85]:
np.dot (arr1,arr2)

array([[3, 0],
       [9, 0]])

In [86]:
arr1@arr2

array([[3, 0],
       [9, 0]])